package com.xiaoyu.rpc.core.transport.netty;

import com.xiaoyu.rpc.common.serialization.Serializer;
import com.xiaoyu.rpc.common.serialization.SerializerCode;
import com.xiaoyu.rpc.common.vo.RpcRequest;
import com.xiaoyu.rpc.common.vo.RpcResponse;
import com.xiaoyu.rpc.core.client.ChannelProvider;
import com.xiaoyu.rpc.core.client.NettyRpcClientHandler;
import com.xiaoyu.rpc.core.config.RpcConfig;
import com.xiaoyu.rpc.core.protocol.Protocol;
import com.xiaoyu.rpc.core.protocol.ProtocolFactory;
import com.xiaoyu.rpc.core.transport.TransportClient;
import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import lombok.extern.slf4j.Slf4j;

import java.net.InetSocketAddress;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.TimeUnit;

@Slf4j
public class NettyTransportClient implements TransportClient {

    private static volatile EventLoopGroup eventLoopGroup;
    private static volatile Bootstrap bootstrap;

    private static Bootstrap getBootstrap() {
        if (bootstrap == null) {
            synchronized (NettyTransportClient.class) {
                if (bootstrap == null) {
                    eventLoopGroup = new NioEventLoopGroup();
                    Bootstrap newBootstrap = new Bootstrap();
                    newBootstrap.group(eventLoopGroup)
                            .channel(NioSocketChannel.class)
                            .handler(new ChannelInitializer<SocketChannel>() {
                                @Override
                                protected void initChannel(SocketChannel ch) {
                                    String protocolName = RpcConfig.getInstance().getProtocol();
                                    Protocol protocol = ProtocolFactory.getProtocol(protocolName);
                                    protocol.config(ch.pipeline(), false, null);
                                }
                            });
                    bootstrap = newBootstrap;
                }
            }
        }
        return bootstrap;
    }

    @Override
    public Object sendRequest(RpcRequest request, InetSocketAddress address) {
        String protocolName = RpcConfig.getInstance().getProtocol();

        try {
            // 使用 ChannelProvider 获取连接
            Channel channel = ChannelProvider.get(address, getBootstrap());
            if (channel == null || !channel.isActive()) {
                throw new RuntimeException("无法连接到服务器: " + address);
            }

            // Reuse handler from pipeline
            NettyRpcClientHandler clientHandler = channel.pipeline().get(NettyRpcClientHandler.class);
            if (clientHandler == null) {
                // Should be added by initChannel, but for safety in some custom protocols:
                clientHandler = new NettyRpcClientHandler();
                channel.pipeline().addLast(clientHandler);
            }

            // Generate ID and set to request
            String requestId = java.util.UUID.randomUUID().toString();
            // Use reflection or builder if setter not available, but since we regenerated
            // proto, we should use builder properly
            // However, RpcRequest is immutable if generated by Proto?
            // Wait, RpcRequest.java is generated. It has a Builder.
            // But the signature of sendRequest takes RpcRequest, which is already built.
            // We need to rebuild it with the ID.

            RpcRequest.Builder builder = request.toBuilder();
            builder.setRequestId(requestId);
            RpcRequest newRequest = builder.build();

            CompletableFuture<Object> resultFuture = new CompletableFuture<>();
            clientHandler.addFuture(requestId, resultFuture);

            Protocol protocol = ProtocolFactory.getProtocol(protocolName);
            // Pass the handler so protocol can ensure it's in pipeline if needed (double
            // check)
            protocol.sendRequest(channel, newRequest, clientHandler);

            Object result = resultFuture.get(5, TimeUnit.SECONDS);

            if (result instanceof RpcResponse) {
                RpcResponse rpcResponse = (RpcResponse) result;

                if (!"Success".equals(rpcResponse.getMessage())) {
                    throw new RuntimeException("服务端报错: " + rpcResponse.getMessage());
                }
                return rpcResponse;

            } else {
                throw new RuntimeException("服务端返回的不是 RpcResponse 类型");
            }
        } catch (Exception e) {
            throw new RuntimeException("RPC请求发送失败", e);
        }
    }
}
