rpc:
  protocol: "http2"
  server-host: "127.0.0.1"
  server-port: 8080
  registry: "nacos"
  registry-address: "127.0.0.1:8848"
  serializer: "KRYO"
  proxy: "bytebuddy"
  load-balancer: "roundrobin"
