# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rpc_meta.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rpc_meta.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erpc_meta.proto\"b\n\nRpcRequest\x12\x16\n\x0einterface_name\x18\x01 \x01(\t\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12\x13\n\x0bparam_types\x18\x03 \x03(\t\x12\x12\n\nparameters\x18\x04 \x03(\x0c\",\n\x0bRpcResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0f\n\x07message\x18\x02 \x01(\t22\n\x0bGrpcService\x12#\n\x06handle\x12\x0b.RpcRequest\x1a\x0c.RpcResponseB\x1c\n\x18\x63om.xiaoyu.rpc.common.voP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_meta_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.xiaoyu.rpc.common.voP\001'
  _globals['_RPCREQUEST']._serialized_start=18
  _globals['_RPCREQUEST']._serialized_end=116
  _globals['_RPCRESPONSE']._serialized_start=118
  _globals['_RPCRESPONSE']._serialized_end=162
  _globals['_GRPCSERVICE']._serialized_start=164
  _globals['_GRPCSERVICE']._serialized_end=214
# @@protoc_insertion_point(module_scope)
