syntax = "proto3";

option java_package = "com.xiaoyu.rpc.common.vo";
option java_multiple_files = true;

enum RpcStatusCode {
  RPC_STATUS_UNSPECIFIED = 0;
  SUCCESS = 1;
  SERVICE_NOT_FOUND = 2;
  METHOD_NOT_FOUND = 3;
  INVALID_ARGUMENT = 4;
  SERVER_BUSY = 5;
  BUSINESS_ERROR = 6;
  INTERNAL_ERROR = 7;
  TIMEOUT = 8;
  UNAVAILABLE = 9;
  CLIENT_CLOSED = 10;
}

message RpcRequest {
  string interface_name = 1;
  string method_name = 2;
  repeated string param_types = 3;
  repeated bytes parameters = 4;
  string request_id = 5;
  map<string, string> metadata = 6;
}

message RpcResponse {
  bytes data = 1;
  string message = 2;
  string request_id = 3;
  RpcStatusCode status_code = 4;
  string error_type = 5;
}

service GrpcService {
  rpc handle (RpcRequest) returns (RpcResponse);
}
