// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: rpc_meta.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 3. 对应你的 RpcRequest
type RpcRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 对应 String interfaceName
	InterfaceName string `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	// 对应 String methodName
	MethodName string `protobuf:"bytes,2,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	// 对应 Class<?>[] paramTypes
	// Proto存不了Class对象，只能存全类名(String)，比如 "java.lang.String"
	ParamTypes []string `protobuf:"bytes,3,rep,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty"`
	// 对应 Object[] parameters
	// Proto存不了Object，必须存成二进制(bytes)。
	// 这里用 repeated 表示数组
	Parameters [][]byte `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// 请求ID，用于多路复用
	RequestId     string `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcRequest) Reset() {
	*x = RpcRequest{}
	mi := &file_rpc_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcRequest) ProtoMessage() {}

func (x *RpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcRequest.ProtoReflect.Descriptor instead.
func (*RpcRequest) Descriptor() ([]byte, []int) {
	return file_rpc_meta_proto_rawDescGZIP(), []int{0}
}

func (x *RpcRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *RpcRequest) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *RpcRequest) GetParamTypes() []string {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

func (x *RpcRequest) GetParameters() [][]byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RpcRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// 4. 对应你的 RpcResponse
type RpcResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 对应 Object data
	// 同样无法存Object，只能存序列化后的二进制
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 对应 String message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 请求ID，用于多路复用
	RequestId     string `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_rpc_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_rpc_meta_proto_rawDescGZIP(), []int{1}
}

func (x *RpcResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RpcResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RpcResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_rpc_meta_proto protoreflect.FileDescriptor

const file_rpc_meta_proto_rawDesc = "" +
	"\n" +
	"\x0erpc_meta.proto\"\xb4\x01\n" +
	"\n" +
	"RpcRequest\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x1f\n" +
	"\vmethod_name\x18\x02 \x01(\tR\n" +
	"methodName\x12\x1f\n" +
	"\vparam_types\x18\x03 \x03(\tR\n" +
	"paramTypes\x12\x1e\n" +
	"\n" +
	"parameters\x18\x04 \x03(\fR\n" +
	"parameters\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"Z\n" +
	"\vRpcResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId22\n" +
	"\vGrpcService\x12#\n" +
	"\x06handle\x12\v.RpcRequest\x1a\f.RpcResponseB*\n" +
	"\x18com.xiaoyu.rpc.common.voP\x01Z\fgo_client/pbb\x06proto3"

var (
	file_rpc_meta_proto_rawDescOnce sync.Once
	file_rpc_meta_proto_rawDescData []byte
)

func file_rpc_meta_proto_rawDescGZIP() []byte {
	file_rpc_meta_proto_rawDescOnce.Do(func() {
		file_rpc_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_meta_proto_rawDesc), len(file_rpc_meta_proto_rawDesc)))
	})
	return file_rpc_meta_proto_rawDescData
}

var file_rpc_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_meta_proto_goTypes = []any{
	(*RpcRequest)(nil),  // 0: RpcRequest
	(*RpcResponse)(nil), // 1: RpcResponse
}
var file_rpc_meta_proto_depIdxs = []int32{
	0, // 0: GrpcService.handle:input_type -> RpcRequest
	1, // 1: GrpcService.handle:output_type -> RpcResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_meta_proto_init() }
func file_rpc_meta_proto_init() {
	if File_rpc_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_meta_proto_rawDesc), len(file_rpc_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_meta_proto_goTypes,
		DependencyIndexes: file_rpc_meta_proto_depIdxs,
		MessageInfos:      file_rpc_meta_proto_msgTypes,
	}.Build()
	File_rpc_meta_proto = out.File
	file_rpc_meta_proto_goTypes = nil
	file_rpc_meta_proto_depIdxs = nil
}
